% This is an autogenerated sample test for file RobustKalmanFilter.m
classdef testRobustKalmanFilter < matlab.unittest.TestCase
    properties (MethodSetupParameter)
        seed = {0,10,20,30,40,50};
        c = {1,1e-5,1e-10};
    end
    properties
        sys
        y
    end
    methods (TestMethodSetup)
        function methodSetup(testCase,seed, c)
            rng(seed);
            Q = 0.8;
            % Measurement noise variance
            R = 2;
            %% Data generation
            % Number of iterations
            N = 300;
            % True State and measurement
            x = zeros(N,1);
            testCase.y = zeros(N,1);
            % True initial state
            x(1) = randn;
            % First measurement
            testCase.y(1) = x(1) + sqrt(Q)*randn;
            % Update true state and measurements
            for i=2:N
                x(i) = x(i-1) + sqrt(Q)*randn;
                testCase.y(i) = x(i) + sqrt(R)*randn;
            end
            %% Nominal process
            A = 1; B = [sqrt(2.0) 0]; C = 1; D = [0 sqrt(1.6)];
            n=size(A,1); p=size(C,1); m=size(B,2); T=size(testCase.y,1);
            cN = maxtol(A,B,C,D,0,2*n);
            if c>cN
                warning('Tolerance c is too large: the filter gain may not exist')
            end
            testCase.sys = struct("A",A,"B",B,"C",C,"D",D);
        end
    end
    methods (Test)

        function test_SameInputEachStep(testCase,c)
            n=size(testCase.sys.A,1);
            p=size(testCase.sys.C,1);
            T=size(testCase.y,1);
            % init
            x=zeros(T,n);       x1=zeros(T,n);
            V=zeros(n,n,T+1);   V1=zeros(n,n,T+1);
            P=zeros(n,n,T+1);   P1=zeros(n,n,T+1);
            G=zeros(n,p,T+1);   G1=zeros(n,p,T+1);
            th=zeros(T,1);      th1=zeros(T,1);
            V(:,:,1)=eye(n);    V1(:,:,1)=eye(n);

            % Exercise the function RobustKalmanFilter
            for k=1:T
                [x(k+1,:), V(:,:,k+1), G(:,:,k+1), P(:,:,k+1), th(k)] = RobustKalmanFilter(testCase.sys, V1(:,:,k), x1(k,:), testCase.y(k,:), c);
                [x1(k+1,:), V1(:,:,k+1), G1(:,:,k+1), P1(:,:,k+1), th1(k)] = ...
                    rkiteration(testCase.sys.A,testCase.sys.B, ...
                    testCase.sys.C,testCase.sys.D,V1(:,:,k),0,c,x1(k,:),testCase.y(k,:));
            end
            testCase.verifyTrue(all(isapprox(x, x1, "veryloose")));
            testCase.verifyTrue(all(isapprox(V, V1, "veryloose")));
            testCase.verifyTrue(all(isapprox(G, G1, "veryloose")));
            testCase.verifyTrue(all(isapprox(P, P1, "veryloose")));
            testCase.verifyTrue(all(isapprox(th1, 1./th, "veryloose")));
        end
        function test_SameCompleteSequence(testCase,c)
            n=size(testCase.sys.A,1);
            p=size(testCase.sys.C,1);
            T=size(testCase.y,1);
            % init
            x=zeros(T,n);       x1=zeros(T,n);
            V=zeros(n,n,T+1);   V1=zeros(n,n,T+1);
            P=zeros(n,n,T+1);   P1=zeros(n,n,T+1);
            G=zeros(n,p,T+1);   G1=zeros(n,p,T+1);
            th=zeros(T,1);      th1=zeros(T,1);
            V(:,:,1)=eye(n);    V1(:,:,1)=eye(n);

            % Exercise the function RobustKalmanFilter
            for k=1:T
                [x(k+1,:), V(:,:,k+1), G(:,:,k+1), P(:,:,k+1), th(k)] = RobustKalmanFilter(testCase.sys, V(:,:,k), x(k,:), testCase.y(k,:), c);
                [x1(k+1,:), V1(:,:,k+1), G1(:,:,k+1), P1(:,:,k+1), th1(k)] = ...
                    rkiteration(testCase.sys.A,testCase.sys.B, ...
                    testCase.sys.C,testCase.sys.D,V1(:,:,k),0,c,x1(k,:),testCase.y(k,:));
            end
            testCase.verifyTrue(all(isapprox(x, x1, "veryloose")));
            testCase.verifyTrue(all(isapprox(V, V1, "veryloose")));
            testCase.verifyTrue(all(isapprox(G, G1, "veryloose")));
            testCase.verifyTrue(all(isapprox(P, P1, "veryloose")));
            testCase.verifyTrue(all(isapprox(th1, 1./th, "veryloose")));
        end
    end
    methods (TestClassSetup)

        function classSetup1(~)
            % Set up shared state for all tests.
            addpath("..\")
        end

    end
end