% This is an autogenerated sample test for file LagrangeMultiplier.m
classdef testLagrangeMultiplier < matlab.unittest.TestCase
    properties (TestParameter)
        dim = struct('small',10,'medium',20,'large',30);
        type = {"fast", "normal"}
    end
    properties (MethodSetupParameter)
        seed = {0,10,20,30};
    end
    methods (TestMethodSetup)
        function methodSetup(~,seed)
            rng(seed);
        end
    end
    methods (Test)
        function testEachType(testCase, dim, type)
            P = random_cov(dim);
            c = 2;

            % Exercise the function LagrangeMultiplier
            lambda = LagrangeMultiplier(P, c, type);

            testCase.verifyTrue(abs(gammafun(lambda, P, c, type)) <= 1e-9 );
        end
        function testCrossType(testCase, dim)
            P = random_cov(dim);
            c = 2;

            % Exercise the function LagrangeMultiplier
            lambda_fast = LagrangeMultiplier(P, c, "fast");
            lambda_normal = LagrangeMultiplier(P, c, "normal");

            testCase.verifyTrue(isapprox(lambda_normal, lambda_fast, "tight") );
        end
    end

    methods (TestClassSetup)

        function classSetup1(~)
            % Set up shared state for all tests.
            addpath("..\")
        end

    end
end